# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - very-basic-flask-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a22747b8fe4840d5848b9bea3790b7e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_38bee29836e547bf91364eb87100dd92 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a22747b8fe4840d5848b9bea3790b7e8 }}/onthejeep/flaskbase:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'very-basic-flask-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d5505a9b541c4bd69a0d871980271094 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a22747b8fe4840d5848b9bea3790b7e8 }}/onthejeep/flaskbase:${{ github.sha }}'